### ISSUE TITLE
What makes a demo “old Skool”?

### ISSUE THREAD

**Issue by gtackett** [patsie75/awk-demo#2]
When these were mentioned on comp.lang.awk a few weeks back, several responders didn’t know what you meant by “old skool”. (I don’t know either.)

- Can you explain what the characteristic(s) is/ are that distinguish an “old skool” demo from whatever other kind(s) of demo you apparently have in mind? Part of that explanation might be to tell what is the reason for not spelling “school” in the standard way.

- It might also be helpful to readers if you state clearly what the thing(s) is (or are) that your demo is intended to demonstrate.

If you can do these two things, perhaps the readers at comp.lang.awk will be more interested, IF what you’re demonstrating is sufficiently interesting to them.

**Comment by patsie75** [comment]
From Wikipedia (https://en.wikipedia.org/wiki/Demoscene): 

The demoscene is an international [computer art](https://en.wikipedia.org/wiki/Computer_art) [subculture](https://en.wikipedia.org/wiki/Subculture) focused on producing demos: self-contained, sometimes extremely small, computer programs that produce [audiovisual](https://en.wikipedia.org/wiki/Audiovisual) presentations. The purpose of a demo is to show off [programming](https://en.wikipedia.org/wiki/Computer_programming), visual art, and musical skills. Demos and other demoscene productions (graphics, music, videos, games) are shared at festivals known as [demoparties](https://en.wikipedia.org/wiki/Demoscene#Parties), voted on by those who attend and released online.

[...]
Demoscene productions can be made with the latest consumer technology or with vintage home computers and consoles.
**Often terms "newschool" and "oldskool" are vaguely used to describe products for newer and older computers. In the oldskool department techniques of the past like ASCII/[ANSI art](https://en.wikipedia.org/wiki/ANSI_art), pixel graphics, [chipmusic](https://en.wikipedia.org/wiki/Chiptune) are constantly being used.**

**Comment by gtackett** [comment]
Thank you, Patsie. Your explanation has helped me to understand what the goals and style of your demos are all about.
